### ISSUE TITLE
abu_said_rebels (Timurid Princes Event) causing crash

### ISSUE THREAD

**Issue by wjpang** [Missions-Expanded/Innocent-Eu4-mod#106]
https://discord.com/channels/431065910040854539/433369138526683146/983098215790440498

**Comment by Stiopa866** [comment]
Fixed by [efabf04](https://github.com/Missions-Expanded/Innocent-Eu4-mod/commit/efabf04f0e7635e2f6db0bb8e7a6da57bb51f906)
